import type { ProviderPreset } from './integrations.js';

/**
 * Starting points for the Add Provider dialog. A preset only fills in
 * defaults -- every field stays editable, and anything not listed here can be
 * added as an OpenAI-compatible or custom provider without code changes.
 *
 * Endpoints, auth styles and discovery paths were verified against each
 * provider's documentation (see docs/UNIVERSAL_AI_RESEARCH.md). Providers
 * that were not verified are deliberately left out rather than guessed.
 */
export const PROVIDER_PRESETS: ProviderPreset[] = [
  /* ---------------------------------------------------------------- built-in */
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://api.openai.com/v1',
    baseUrlEditable: false,
    authMethod: 'bearer',
    apiKeyRequired: true,
    docsUrl: 'https://developers.openai.com/api/reference/resources/chat',
    description: 'GPT models through the Chat Completions API.',
    options: { tokenParameter: 'max_completion_tokens' },
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'builtin',
    kind: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    baseUrlEditable: false,
    authMethod: 'header',
    authHeaderName: 'x-api-key',
    apiKeyRequired: true,
    docsUrl: 'https://platform.claude.com/docs/en/api/messages',
    description: 'Claude models through the native Messages API.',
    options: { anthropicVersion: '2023-06-01' },
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    category: 'builtin',
    kind: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com',
    baseUrlEditable: false,
    authMethod: 'header',
    authHeaderName: 'x-goog-api-key',
    apiKeyRequired: true,
    docsUrl: 'https://ai.google.dev/gemini-api/docs/openai',
    description: 'Gemini models. Token limits come from the native model list.',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://YOUR-RESOURCE.openai.azure.com/openai/v1',
    baseUrlEditable: true,
    authMethod: 'header',
    authHeaderName: 'api-key',
    apiKeyRequired: true,
    docsUrl: 'https://learn.microsoft.com/en-us/azure/ai-foundry/openai/api-version-lifecycle',
    description: 'The v1 API. Use your deployment name as the model id.',
  },
  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1',
    baseUrlEditable: true,
    authMethod: 'bearer',
    apiKeyRequired: true,
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/inference-chat-completions-mantle.html',
    description:
      'OpenAI-compatible endpoint with a Bedrock API key. Only models whose card lists Chat Completions work; enter the model id manually.',
    options: { modelsPath: '' },
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    baseUrlEditable: false,
    authMethod: 'bearer',
    apiKeyRequired: true,
    docsUrl: 'https://openrouter.ai/docs/quickstart',
    description: 'Hundreds of models behind one key, with rich capability data.',
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://api.groq.com/openai/v1',
    baseUrlEditable: false,
    authMethod: 'bearer',
    apiKeyRequired: true,
    docsUrl: 'https://console.groq.com/docs/openai',
    description: 'Fast inference for open models.',
  },
  {
    id: 'together',
    name: 'Together AI',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://api.together.ai/v1',
    baseUrlEditable: false,
    authMethod: 'bearer',
    apiKeyRequired: true,
    docsUrl: 'https://docs.together.ai/docs/openai-api-compatibility',
    description: 'Open models with namespaced ids.',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    baseUrlEditable: false,
    authMethod: 'bearer',
    apiKeyRequired: true,
    docsUrl: 'https://docs.fireworks.ai/tools-sdks/openai-compatibility',
    description: 'Open models on Fireworks.',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'builtin',
    kind: 'openai-compatible',
    baseUrl: 'https://router.huggingface.co/v1',
    baseUrlEditable: false,
    authMethod: 'bearer',
    apiKeyRequired: true,
    docsUrl: 'https://huggingface.co/docs/inference-providers/index',
    description: 'Inference Providers router. Suffix a model with :fastest or :cheapest to pick a backend.',
  },

  /* ------------------------------------------------------ openai-compatible */
  {
    id: 'openai-compatible',
    name: 'OpenAI-compatible API',
    category: 'openai-compatible',
    kind: 'openai-compatible',
    baseUrl: '',
    baseUrlEditable: true,
    authMethod: 'bearer',
    apiKeyRequired: false,
    docsUrl: 'https://developers.openai.com/api/reference/resources/chat',
    description: 'Any server that speaks OpenAI Chat Completions: LiteLLM, a gateway, a hosted service.',
  },

  /* ------------------------------------------------------------------ local */
  {
    id: 'ollama',
    name: 'Ollama',
    category: 'local',
    kind: 'ollama',
    baseUrl: 'http://localhost:11434',
    baseUrlEditable: true,
    authMethod: 'none',
    apiKeyRequired: false,
    docsUrl: 'https://docs.ollama.com/api/openai-compatibility.md',
    description: 'Models pulled with Ollama. Capabilities and context size come from Ollama itself.',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    category: 'local',
    kind: 'openai-compatible',
    baseUrl: 'http://localhost:1234/v1',
    baseUrlEditable: true,
    authMethod: 'none',
    apiKeyRequired: false,
    docsUrl: 'https://lmstudio.ai/docs/developer/openai-compat',
    description: "LM Studio's local server. Start it from the Developer tab.",
  },
  {
    id: 'vllm',
    name: 'vLLM',
    category: 'local',
    kind: 'openai-compatible',
    baseUrl: 'http://localhost:8000/v1',
    baseUrlEditable: true,
    authMethod: 'none',
    apiKeyRequired: false,
    docsUrl: 'https://docs.vllm.ai/en/latest/serving/online_serving/openai_compatible_server/',
    description: 'Tool calling needs --enable-auto-tool-choice and a --tool-call-parser.',
  },
  {
    id: 'llamacpp',
    name: 'llama.cpp server',
    category: 'local',
    kind: 'openai-compatible',
    baseUrl: 'http://127.0.0.1:8080/v1',
    baseUrlEditable: true,
    authMethod: 'none',
    apiKeyRequired: false,
    docsUrl: 'https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md',
    description: 'llama-server serves one model at a time.',
  },

  /* ----------------------------------------------------------------- custom */
  {
    id: 'custom',
    name: 'Custom provider',
    category: 'custom',
    kind: 'openai-compatible',
    baseUrl: '',
    baseUrlEditable: true,
    authMethod: 'bearer',
    apiKeyRequired: false,
    docsUrl: 'https://developers.openai.com/api/reference/resources/chat',
    description:
      'Full control: authentication header, custom headers, request paths and timeout, for any Chat Completions–style endpoint.',
  },
];

export function presetById(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((p) => p.id === id);
}
