// Generated by scripts/collect-credits.mjs from the installed packages.
// Run `npm run credits` after changing dependencies; do not edit by hand.

export interface Credit {
  name: string;
  version: string;
  license: string;
  homepage: string;
  /** What it does in LoCrew, where that is not obvious. */
  role: string | null;
}

export const CREDITS: Credit[] = [
  {
    "name": "@a2a-js/sdk",
    "version": "1.2.0",
    "license": "Apache-2.0",
    "homepage": "https://github.com/a2aproject/a2a-js",
    "role": "Agent2Agent protocol"
  },
  {
    "name": "@anthropic-ai/claude-agent-sdk",
    "version": "0.3.278",
    "license": "Own licence",
    "homepage": "https://github.com/anthropics/claude-agent-sdk-typescript",
    "role": "Runs Claude Code agents"
  },
  {
    "name": "@anthropic-ai/sdk",
    "version": "0.127.0",
    "license": "MIT",
    "homepage": "github:anthropics/anthropic-sdk-typescript",
    "role": "Anthropic Messages API"
  },
  {
    "name": "@fontsource-variable/inter",
    "version": "5.3.0",
    "license": "OFL-1.1",
    "homepage": "https://fontsource.org/fonts/inter",
    "role": "Inter, the interface typeface"
  },
  {
    "name": "@modelcontextprotocol/sdk",
    "version": "1.30.0",
    "license": "MIT",
    "homepage": "https://modelcontextprotocol.io",
    "role": "MCP client and server"
  },
  {
    "name": "@openai/codex-sdk",
    "version": "0.155.1",
    "license": "Apache-2.0",
    "homepage": "https://github.com/openai/codex",
    "role": "Runs OpenAI Codex agents"
  },
  {
    "name": "@radix-ui/react-*",
    "version": "7 packages",
    "license": "MIT",
    "homepage": "https://www.radix-ui.com/primitives",
    "role": "Accessible dialogs, menus and tooltips"
  },
  {
    "name": "better-sqlite3",
    "version": "11.10.0",
    "license": "MIT",
    "homepage": "http://github.com/WiseLibs/better-sqlite3",
    "role": "Local database"
  },
  {
    "name": "class-variance-authority",
    "version": "0.7.1",
    "license": "Apache-2.0",
    "homepage": "https://github.com/joe-bell/cva#readme",
    "role": "Styling"
  },
  {
    "name": "clsx",
    "version": "2.1.1",
    "license": "MIT",
    "homepage": "lukeed/clsx",
    "role": "Styling"
  },
  {
    "name": "drizzle-orm",
    "version": "0.38.4",
    "license": "Apache-2.0",
    "homepage": "https://orm.drizzle.team",
    "role": "Database schema and queries"
  },
  {
    "name": "electron",
    "version": "34.5.8",
    "license": "MIT",
    "homepage": "https://github.com/electron/electron",
    "role": "Desktop application shell"
  },
  {
    "name": "highlight.js",
    "version": "11.12.0",
    "license": "BSD-3-Clause",
    "homepage": "https://highlightjs.org/",
    "role": "Code highlighting"
  },
  {
    "name": "lucide-react",
    "version": "1.47.0",
    "license": "ISC",
    "homepage": "https://lucide.dev",
    "role": "Icons"
  },
  {
    "name": "react",
    "version": "19.3.0",
    "license": "MIT",
    "homepage": "https://react.dev/",
    "role": "User interface"
  },
  {
    "name": "react-dom",
    "version": "19.3.0",
    "license": "MIT",
    "homepage": "https://react.dev/",
    "role": "User interface"
  },
  {
    "name": "react-markdown",
    "version": "9.1.0",
    "license": "MIT",
    "homepage": "remarkjs/react-markdown",
    "role": "Message rendering"
  },
  {
    "name": "remark-gfm",
    "version": "4.0.1",
    "license": "MIT",
    "homepage": "remarkjs/remark-gfm",
    "role": "Message rendering"
  },
  {
    "name": "tailwind-merge",
    "version": "3.7.0",
    "license": "MIT",
    "homepage": "https://github.com/dcastil/tailwind-merge",
    "role": "Styling"
  },
  {
    "name": "zod",
    "version": "4.6.5",
    "license": "MIT",
    "homepage": "https://zod.dev",
    "role": "Validation of every IPC payload"
  },
  {
    "name": "zustand",
    "version": "5.0.15",
    "license": "MIT",
    "homepage": "https://github.com/pmndrs/zustand",
    "role": "Renderer state"
  }
];
