/**
 * Regenerates src/renderer/src/lib/credits.ts from what is actually installed.
 *
 * The About screen credits the projects LoCrew ships, so the list has to come
 * from node_modules rather than from memory: names, versions and licences are
 * read from each package's own package.json. Run `npm run credits` after
 * changing dependencies.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '..');
const manifest = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

/** Build tools are not shipped; Electron is, so it is named explicitly. */
const SHIPPED_DEV_DEPENDENCIES = ['electron'];

/** What each project does here, for the ones a reader would wonder about. */
const ROLES = {
  electron: 'Desktop application shell',
  react: 'User interface',
  'react-dom': 'User interface',
  '@anthropic-ai/claude-agent-sdk': 'Runs Claude Code agents',
  '@openai/codex-sdk': 'Runs OpenAI Codex agents',
  '@anthropic-ai/sdk': 'Anthropic Messages API',
  '@modelcontextprotocol/sdk': 'MCP client and server',
  '@a2a-js/sdk': 'Agent2Agent protocol',
  'better-sqlite3': 'Local database',
  'drizzle-orm': 'Database schema and queries',
  zod: 'Validation of every IPC payload',
  zustand: 'Renderer state',
  'react-markdown': 'Message rendering',
  'remark-gfm': 'Message rendering',
  'highlight.js': 'Code highlighting',
  'lucide-react': 'Icons',
  '@fontsource-variable/inter': 'Inter, the interface typeface',
  tailwindcss: 'Styling',
  'tailwind-merge': 'Styling',
  'class-variance-authority': 'Styling',
  clsx: 'Styling',
};

const names = [
  ...Object.keys(manifest.dependencies ?? {}),
  ...SHIPPED_DEV_DEPENDENCIES.filter((name) => manifest.devDependencies?.[name]),
];

/** Radix ships as a dozen packages; they are one project to a reader. */
const radix = names.filter((name) => name.startsWith('@radix-ui/'));
const singles = names.filter((name) => !name.startsWith('@radix-ui/'));

const entries = [];
for (const name of singles) {
  entries.push(read(name));
}
if (radix.length) {
  const first = read(radix[0]);
  entries.push({
    name: '@radix-ui/react-*',
    version: `${radix.length} packages`,
    license: first.license,
    homepage: 'https://www.radix-ui.com/primitives',
    role: 'Accessible dialogs, menus and tooltips',
  });
}

function read(name) {
  const path = join(root, 'node_modules', name, 'package.json');
  const pkg = JSON.parse(readFileSync(path, 'utf8'));
  const declared =
    typeof pkg.license === 'string'
      ? pkg.license
      : (pkg.license?.type ?? (Array.isArray(pkg.licenses) ? pkg.licenses.map((l) => l.type).join(', ') : ''));
  // "SEE LICENSE IN README.md" and friends are pointers, not licence names.
  const license = !declared ? 'See package' : /^SEE LICEN[CS]E/i.test(declared) ? 'Own licence' : declared;
  const homepage =
    typeof pkg.homepage === 'string'
      ? pkg.homepage
      : typeof pkg.repository === 'string'
        ? pkg.repository
        : (pkg.repository?.url ?? '').replace(/^git\+/, '').replace(/\.git$/, '');
  return { name, version: pkg.version, license, homepage, role: ROLES[name] ?? null };
}

entries.sort((a, b) => a.name.localeCompare(b.name));

const file = `// Generated by scripts/collect-credits.mjs from the installed packages.
// Run \`npm run credits\` after changing dependencies; do not edit by hand.

export interface Credit {
  name: string;
  version: string;
  license: string;
  homepage: string;
  /** What it does in LoCrew, where that is not obvious. */
  role: string | null;
}

export const CREDITS: Credit[] = ${JSON.stringify(entries, null, 2)};
`;

const target = join(root, 'src', 'renderer', 'src', 'lib', 'credits.ts');
writeFileSync(target, file, 'utf8');
console.log(`Wrote ${target} (${entries.length} projects).`);
